/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestsImport } from './routes/tests'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as WithMenuRouteImport } from './routes/_withMenu/route'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIdImport } from './routes/profile.$id'
import { Route as MenuIdImport } from './routes/menu.$id'
import { Route as AccountProfileTypeUpdatedImport } from './routes/account/profile-type-updated'
import { Route as AccountLanguageImport } from './routes/account/language'
import { Route as WithMenuSelectionsImport } from './routes/_withMenu/selections'
import { Route as WithMenuMapImport } from './routes/_withMenu/map'
import { Route as WithMenuEarnImport } from './routes/_withMenu/earn'
import { Route as WithMenuAccountImport } from './routes/_withMenu/account'
import { Route as TipsPlaceIdRouteImport } from './routes/tips.$placeId/route'
import { Route as TipsPlaceIdIndexImport } from './routes/tips.$placeId/index'
import { Route as TipsPlaceIdSuccessImport } from './routes/tips.$placeId/success'
import { Route as TipsPlaceIdProfileImport } from './routes/tips.$placeId/profile'
import { Route as TipsPlaceIdInfoImport } from './routes/tips.$placeId/info'
import { Route as TipsPlaceIdErrorImport } from './routes/tips.$placeId/error'
import { Route as TipsPlaceIdAssetsImport } from './routes/tips.$placeId/assets'
import { Route as ProfileIdFundraisingImport } from './routes/profile.$id.fundraising'
import { Route as AccountMyProfileViewImport } from './routes/account/my-profile.view'
import { Route as AccountMyProfileEditImport } from './routes/account/my-profile.edit'
import { Route as WithMenuSelectionsIdImport } from './routes/_withMenu/selections.$id'
import { Route as TipsPlaceIdInputRouteImport } from './routes/tips.$placeId/input/route'
import { Route as TipsPlaceIdInputConfirmImport } from './routes/tips.$placeId/input/confirm'
import { Route as TipsPlaceIdInputAmountImport } from './routes/tips.$placeId/input/amount'

// Create/Update Routes

const TestsRoute = TestsImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const WithMenuRouteRoute = WithMenuRouteImport.update({
  id: '/_withMenu',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIdRoute = ProfileIdImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRoute,
} as any)

const MenuIdRoute = MenuIdImport.update({
  id: '/menu/$id',
  path: '/menu/$id',
  getParentRoute: () => rootRoute,
} as any)

const AccountProfileTypeUpdatedRoute = AccountProfileTypeUpdatedImport.update({
  id: '/account/profile-type-updated',
  path: '/account/profile-type-updated',
  getParentRoute: () => rootRoute,
} as any)

const AccountLanguageRoute = AccountLanguageImport.update({
  id: '/account/language',
  path: '/account/language',
  getParentRoute: () => rootRoute,
} as any)

const WithMenuSelectionsRoute = WithMenuSelectionsImport.update({
  id: '/selections',
  path: '/selections',
  getParentRoute: () => WithMenuRouteRoute,
} as any)

const WithMenuMapRoute = WithMenuMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => WithMenuRouteRoute,
} as any)

const WithMenuEarnRoute = WithMenuEarnImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => WithMenuRouteRoute,
} as any)

const WithMenuAccountRoute = WithMenuAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WithMenuRouteRoute,
} as any)

const TipsPlaceIdRouteRoute = TipsPlaceIdRouteImport.update({
  id: '/tips/$placeId',
  path: '/tips/$placeId',
  getParentRoute: () => rootRoute,
} as any)

const TipsPlaceIdIndexRoute = TipsPlaceIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TipsPlaceIdRouteRoute,
} as any)

const TipsPlaceIdSuccessRoute = TipsPlaceIdSuccessImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => TipsPlaceIdRouteRoute,
} as any)

const TipsPlaceIdProfileRoute = TipsPlaceIdProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TipsPlaceIdRouteRoute,
} as any)

const TipsPlaceIdInfoRoute = TipsPlaceIdInfoImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => TipsPlaceIdRouteRoute,
} as any)

const TipsPlaceIdErrorRoute = TipsPlaceIdErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => TipsPlaceIdRouteRoute,
} as any)

const TipsPlaceIdAssetsRoute = TipsPlaceIdAssetsImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => TipsPlaceIdRouteRoute,
} as any)

const ProfileIdFundraisingRoute = ProfileIdFundraisingImport.update({
  id: '/fundraising',
  path: '/fundraising',
  getParentRoute: () => ProfileIdRoute,
} as any)

const AccountMyProfileViewRoute = AccountMyProfileViewImport.update({
  id: '/account/my-profile/view',
  path: '/account/my-profile/view',
  getParentRoute: () => rootRoute,
} as any)

const AccountMyProfileEditRoute = AccountMyProfileEditImport.update({
  id: '/account/my-profile/edit',
  path: '/account/my-profile/edit',
  getParentRoute: () => rootRoute,
} as any)

const WithMenuSelectionsIdRoute = WithMenuSelectionsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WithMenuSelectionsRoute,
} as any)

const TipsPlaceIdInputRouteRoute = TipsPlaceIdInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => TipsPlaceIdRouteRoute,
} as any)

const TipsPlaceIdInputConfirmRoute = TipsPlaceIdInputConfirmImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => TipsPlaceIdInputRouteRoute,
} as any)

const TipsPlaceIdInputAmountRoute = TipsPlaceIdInputAmountImport.update({
  id: '/amount',
  path: '/amount',
  getParentRoute: () => TipsPlaceIdInputRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_withMenu': {
      id: '/_withMenu'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithMenuRouteImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsImport
      parentRoute: typeof rootRoute
    }
    '/tips/$placeId': {
      id: '/tips/$placeId'
      path: '/tips/$placeId'
      fullPath: '/tips/$placeId'
      preLoaderRoute: typeof TipsPlaceIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/_withMenu/account': {
      id: '/_withMenu/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof WithMenuAccountImport
      parentRoute: typeof WithMenuRouteImport
    }
    '/_withMenu/earn': {
      id: '/_withMenu/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof WithMenuEarnImport
      parentRoute: typeof WithMenuRouteImport
    }
    '/_withMenu/map': {
      id: '/_withMenu/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof WithMenuMapImport
      parentRoute: typeof WithMenuRouteImport
    }
    '/_withMenu/selections': {
      id: '/_withMenu/selections'
      path: '/selections'
      fullPath: '/selections'
      preLoaderRoute: typeof WithMenuSelectionsImport
      parentRoute: typeof WithMenuRouteImport
    }
    '/account/language': {
      id: '/account/language'
      path: '/account/language'
      fullPath: '/account/language'
      preLoaderRoute: typeof AccountLanguageImport
      parentRoute: typeof rootRoute
    }
    '/account/profile-type-updated': {
      id: '/account/profile-type-updated'
      path: '/account/profile-type-updated'
      fullPath: '/account/profile-type-updated'
      preLoaderRoute: typeof AccountProfileTypeUpdatedImport
      parentRoute: typeof rootRoute
    }
    '/menu/$id': {
      id: '/menu/$id'
      path: '/menu/$id'
      fullPath: '/menu/$id'
      preLoaderRoute: typeof MenuIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdImport
      parentRoute: typeof rootRoute
    }
    '/tips/$placeId/input': {
      id: '/tips/$placeId/input'
      path: '/input'
      fullPath: '/tips/$placeId/input'
      preLoaderRoute: typeof TipsPlaceIdInputRouteImport
      parentRoute: typeof TipsPlaceIdRouteImport
    }
    '/_withMenu/selections/$id': {
      id: '/_withMenu/selections/$id'
      path: '/$id'
      fullPath: '/selections/$id'
      preLoaderRoute: typeof WithMenuSelectionsIdImport
      parentRoute: typeof WithMenuSelectionsImport
    }
    '/account/my-profile/edit': {
      id: '/account/my-profile/edit'
      path: '/account/my-profile/edit'
      fullPath: '/account/my-profile/edit'
      preLoaderRoute: typeof AccountMyProfileEditImport
      parentRoute: typeof rootRoute
    }
    '/account/my-profile/view': {
      id: '/account/my-profile/view'
      path: '/account/my-profile/view'
      fullPath: '/account/my-profile/view'
      preLoaderRoute: typeof AccountMyProfileViewImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id/fundraising': {
      id: '/profile/$id/fundraising'
      path: '/fundraising'
      fullPath: '/profile/$id/fundraising'
      preLoaderRoute: typeof ProfileIdFundraisingImport
      parentRoute: typeof ProfileIdImport
    }
    '/tips/$placeId/assets': {
      id: '/tips/$placeId/assets'
      path: '/assets'
      fullPath: '/tips/$placeId/assets'
      preLoaderRoute: typeof TipsPlaceIdAssetsImport
      parentRoute: typeof TipsPlaceIdRouteImport
    }
    '/tips/$placeId/error': {
      id: '/tips/$placeId/error'
      path: '/error'
      fullPath: '/tips/$placeId/error'
      preLoaderRoute: typeof TipsPlaceIdErrorImport
      parentRoute: typeof TipsPlaceIdRouteImport
    }
    '/tips/$placeId/info': {
      id: '/tips/$placeId/info'
      path: '/info'
      fullPath: '/tips/$placeId/info'
      preLoaderRoute: typeof TipsPlaceIdInfoImport
      parentRoute: typeof TipsPlaceIdRouteImport
    }
    '/tips/$placeId/profile': {
      id: '/tips/$placeId/profile'
      path: '/profile'
      fullPath: '/tips/$placeId/profile'
      preLoaderRoute: typeof TipsPlaceIdProfileImport
      parentRoute: typeof TipsPlaceIdRouteImport
    }
    '/tips/$placeId/success': {
      id: '/tips/$placeId/success'
      path: '/success'
      fullPath: '/tips/$placeId/success'
      preLoaderRoute: typeof TipsPlaceIdSuccessImport
      parentRoute: typeof TipsPlaceIdRouteImport
    }
    '/tips/$placeId/': {
      id: '/tips/$placeId/'
      path: '/'
      fullPath: '/tips/$placeId/'
      preLoaderRoute: typeof TipsPlaceIdIndexImport
      parentRoute: typeof TipsPlaceIdRouteImport
    }
    '/tips/$placeId/input/amount': {
      id: '/tips/$placeId/input/amount'
      path: '/amount'
      fullPath: '/tips/$placeId/input/amount'
      preLoaderRoute: typeof TipsPlaceIdInputAmountImport
      parentRoute: typeof TipsPlaceIdInputRouteImport
    }
    '/tips/$placeId/input/confirm': {
      id: '/tips/$placeId/input/confirm'
      path: '/confirm'
      fullPath: '/tips/$placeId/input/confirm'
      preLoaderRoute: typeof TipsPlaceIdInputConfirmImport
      parentRoute: typeof TipsPlaceIdInputRouteImport
    }
  }
}

// Create and export the route tree

interface WithMenuSelectionsRouteChildren {
  WithMenuSelectionsIdRoute: typeof WithMenuSelectionsIdRoute
}

const WithMenuSelectionsRouteChildren: WithMenuSelectionsRouteChildren = {
  WithMenuSelectionsIdRoute: WithMenuSelectionsIdRoute,
}

const WithMenuSelectionsRouteWithChildren =
  WithMenuSelectionsRoute._addFileChildren(WithMenuSelectionsRouteChildren)

interface WithMenuRouteRouteChildren {
  WithMenuAccountRoute: typeof WithMenuAccountRoute
  WithMenuEarnRoute: typeof WithMenuEarnRoute
  WithMenuMapRoute: typeof WithMenuMapRoute
  WithMenuSelectionsRoute: typeof WithMenuSelectionsRouteWithChildren
}

const WithMenuRouteRouteChildren: WithMenuRouteRouteChildren = {
  WithMenuAccountRoute: WithMenuAccountRoute,
  WithMenuEarnRoute: WithMenuEarnRoute,
  WithMenuMapRoute: WithMenuMapRoute,
  WithMenuSelectionsRoute: WithMenuSelectionsRouteWithChildren,
}

const WithMenuRouteRouteWithChildren = WithMenuRouteRoute._addFileChildren(
  WithMenuRouteRouteChildren,
)

interface TipsPlaceIdInputRouteRouteChildren {
  TipsPlaceIdInputAmountRoute: typeof TipsPlaceIdInputAmountRoute
  TipsPlaceIdInputConfirmRoute: typeof TipsPlaceIdInputConfirmRoute
}

const TipsPlaceIdInputRouteRouteChildren: TipsPlaceIdInputRouteRouteChildren = {
  TipsPlaceIdInputAmountRoute: TipsPlaceIdInputAmountRoute,
  TipsPlaceIdInputConfirmRoute: TipsPlaceIdInputConfirmRoute,
}

const TipsPlaceIdInputRouteRouteWithChildren =
  TipsPlaceIdInputRouteRoute._addFileChildren(
    TipsPlaceIdInputRouteRouteChildren,
  )

interface TipsPlaceIdRouteRouteChildren {
  TipsPlaceIdInputRouteRoute: typeof TipsPlaceIdInputRouteRouteWithChildren
  TipsPlaceIdAssetsRoute: typeof TipsPlaceIdAssetsRoute
  TipsPlaceIdErrorRoute: typeof TipsPlaceIdErrorRoute
  TipsPlaceIdInfoRoute: typeof TipsPlaceIdInfoRoute
  TipsPlaceIdProfileRoute: typeof TipsPlaceIdProfileRoute
  TipsPlaceIdSuccessRoute: typeof TipsPlaceIdSuccessRoute
  TipsPlaceIdIndexRoute: typeof TipsPlaceIdIndexRoute
}

const TipsPlaceIdRouteRouteChildren: TipsPlaceIdRouteRouteChildren = {
  TipsPlaceIdInputRouteRoute: TipsPlaceIdInputRouteRouteWithChildren,
  TipsPlaceIdAssetsRoute: TipsPlaceIdAssetsRoute,
  TipsPlaceIdErrorRoute: TipsPlaceIdErrorRoute,
  TipsPlaceIdInfoRoute: TipsPlaceIdInfoRoute,
  TipsPlaceIdProfileRoute: TipsPlaceIdProfileRoute,
  TipsPlaceIdSuccessRoute: TipsPlaceIdSuccessRoute,
  TipsPlaceIdIndexRoute: TipsPlaceIdIndexRoute,
}

const TipsPlaceIdRouteRouteWithChildren =
  TipsPlaceIdRouteRoute._addFileChildren(TipsPlaceIdRouteRouteChildren)

interface ProfileIdRouteChildren {
  ProfileIdFundraisingRoute: typeof ProfileIdFundraisingRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdFundraisingRoute: ProfileIdFundraisingRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof WithMenuRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/tests': typeof TestsRoute
  '/tips/$placeId': typeof TipsPlaceIdRouteRouteWithChildren
  '/account': typeof WithMenuAccountRoute
  '/earn': typeof WithMenuEarnRoute
  '/map': typeof WithMenuMapRoute
  '/selections': typeof WithMenuSelectionsRouteWithChildren
  '/account/language': typeof AccountLanguageRoute
  '/account/profile-type-updated': typeof AccountProfileTypeUpdatedRoute
  '/menu/$id': typeof MenuIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/tips/$placeId/input': typeof TipsPlaceIdInputRouteRouteWithChildren
  '/selections/$id': typeof WithMenuSelectionsIdRoute
  '/account/my-profile/edit': typeof AccountMyProfileEditRoute
  '/account/my-profile/view': typeof AccountMyProfileViewRoute
  '/profile/$id/fundraising': typeof ProfileIdFundraisingRoute
  '/tips/$placeId/assets': typeof TipsPlaceIdAssetsRoute
  '/tips/$placeId/error': typeof TipsPlaceIdErrorRoute
  '/tips/$placeId/info': typeof TipsPlaceIdInfoRoute
  '/tips/$placeId/profile': typeof TipsPlaceIdProfileRoute
  '/tips/$placeId/success': typeof TipsPlaceIdSuccessRoute
  '/tips/$placeId/': typeof TipsPlaceIdIndexRoute
  '/tips/$placeId/input/amount': typeof TipsPlaceIdInputAmountRoute
  '/tips/$placeId/input/confirm': typeof TipsPlaceIdInputConfirmRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof WithMenuRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/tests': typeof TestsRoute
  '/account': typeof WithMenuAccountRoute
  '/earn': typeof WithMenuEarnRoute
  '/map': typeof WithMenuMapRoute
  '/selections': typeof WithMenuSelectionsRouteWithChildren
  '/account/language': typeof AccountLanguageRoute
  '/account/profile-type-updated': typeof AccountProfileTypeUpdatedRoute
  '/menu/$id': typeof MenuIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/tips/$placeId/input': typeof TipsPlaceIdInputRouteRouteWithChildren
  '/selections/$id': typeof WithMenuSelectionsIdRoute
  '/account/my-profile/edit': typeof AccountMyProfileEditRoute
  '/account/my-profile/view': typeof AccountMyProfileViewRoute
  '/profile/$id/fundraising': typeof ProfileIdFundraisingRoute
  '/tips/$placeId/assets': typeof TipsPlaceIdAssetsRoute
  '/tips/$placeId/error': typeof TipsPlaceIdErrorRoute
  '/tips/$placeId/info': typeof TipsPlaceIdInfoRoute
  '/tips/$placeId/profile': typeof TipsPlaceIdProfileRoute
  '/tips/$placeId/success': typeof TipsPlaceIdSuccessRoute
  '/tips/$placeId': typeof TipsPlaceIdIndexRoute
  '/tips/$placeId/input/amount': typeof TipsPlaceIdInputAmountRoute
  '/tips/$placeId/input/confirm': typeof TipsPlaceIdInputConfirmRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_withMenu': typeof WithMenuRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/tests': typeof TestsRoute
  '/tips/$placeId': typeof TipsPlaceIdRouteRouteWithChildren
  '/_withMenu/account': typeof WithMenuAccountRoute
  '/_withMenu/earn': typeof WithMenuEarnRoute
  '/_withMenu/map': typeof WithMenuMapRoute
  '/_withMenu/selections': typeof WithMenuSelectionsRouteWithChildren
  '/account/language': typeof AccountLanguageRoute
  '/account/profile-type-updated': typeof AccountProfileTypeUpdatedRoute
  '/menu/$id': typeof MenuIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/tips/$placeId/input': typeof TipsPlaceIdInputRouteRouteWithChildren
  '/_withMenu/selections/$id': typeof WithMenuSelectionsIdRoute
  '/account/my-profile/edit': typeof AccountMyProfileEditRoute
  '/account/my-profile/view': typeof AccountMyProfileViewRoute
  '/profile/$id/fundraising': typeof ProfileIdFundraisingRoute
  '/tips/$placeId/assets': typeof TipsPlaceIdAssetsRoute
  '/tips/$placeId/error': typeof TipsPlaceIdErrorRoute
  '/tips/$placeId/info': typeof TipsPlaceIdInfoRoute
  '/tips/$placeId/profile': typeof TipsPlaceIdProfileRoute
  '/tips/$placeId/success': typeof TipsPlaceIdSuccessRoute
  '/tips/$placeId/': typeof TipsPlaceIdIndexRoute
  '/tips/$placeId/input/amount': typeof TipsPlaceIdInputAmountRoute
  '/tips/$placeId/input/confirm': typeof TipsPlaceIdInputConfirmRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/onboarding'
    | '/tests'
    | '/tips/$placeId'
    | '/account'
    | '/earn'
    | '/map'
    | '/selections'
    | '/account/language'
    | '/account/profile-type-updated'
    | '/menu/$id'
    | '/profile/$id'
    | '/tips/$placeId/input'
    | '/selections/$id'
    | '/account/my-profile/edit'
    | '/account/my-profile/view'
    | '/profile/$id/fundraising'
    | '/tips/$placeId/assets'
    | '/tips/$placeId/error'
    | '/tips/$placeId/info'
    | '/tips/$placeId/profile'
    | '/tips/$placeId/success'
    | '/tips/$placeId/'
    | '/tips/$placeId/input/amount'
    | '/tips/$placeId/input/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/onboarding'
    | '/tests'
    | '/account'
    | '/earn'
    | '/map'
    | '/selections'
    | '/account/language'
    | '/account/profile-type-updated'
    | '/menu/$id'
    | '/profile/$id'
    | '/tips/$placeId/input'
    | '/selections/$id'
    | '/account/my-profile/edit'
    | '/account/my-profile/view'
    | '/profile/$id/fundraising'
    | '/tips/$placeId/assets'
    | '/tips/$placeId/error'
    | '/tips/$placeId/info'
    | '/tips/$placeId/profile'
    | '/tips/$placeId/success'
    | '/tips/$placeId'
    | '/tips/$placeId/input/amount'
    | '/tips/$placeId/input/confirm'
  id:
    | '__root__'
    | '/'
    | '/_withMenu'
    | '/onboarding'
    | '/tests'
    | '/tips/$placeId'
    | '/_withMenu/account'
    | '/_withMenu/earn'
    | '/_withMenu/map'
    | '/_withMenu/selections'
    | '/account/language'
    | '/account/profile-type-updated'
    | '/menu/$id'
    | '/profile/$id'
    | '/tips/$placeId/input'
    | '/_withMenu/selections/$id'
    | '/account/my-profile/edit'
    | '/account/my-profile/view'
    | '/profile/$id/fundraising'
    | '/tips/$placeId/assets'
    | '/tips/$placeId/error'
    | '/tips/$placeId/info'
    | '/tips/$placeId/profile'
    | '/tips/$placeId/success'
    | '/tips/$placeId/'
    | '/tips/$placeId/input/amount'
    | '/tips/$placeId/input/confirm'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithMenuRouteRoute: typeof WithMenuRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  TestsRoute: typeof TestsRoute
  TipsPlaceIdRouteRoute: typeof TipsPlaceIdRouteRouteWithChildren
  AccountLanguageRoute: typeof AccountLanguageRoute
  AccountProfileTypeUpdatedRoute: typeof AccountProfileTypeUpdatedRoute
  MenuIdRoute: typeof MenuIdRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
  AccountMyProfileEditRoute: typeof AccountMyProfileEditRoute
  AccountMyProfileViewRoute: typeof AccountMyProfileViewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithMenuRouteRoute: WithMenuRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  TestsRoute: TestsRoute,
  TipsPlaceIdRouteRoute: TipsPlaceIdRouteRouteWithChildren,
  AccountLanguageRoute: AccountLanguageRoute,
  AccountProfileTypeUpdatedRoute: AccountProfileTypeUpdatedRoute,
  MenuIdRoute: MenuIdRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
  AccountMyProfileEditRoute: AccountMyProfileEditRoute,
  AccountMyProfileViewRoute: AccountMyProfileViewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_withMenu",
        "/onboarding",
        "/tests",
        "/tips/$placeId",
        "/account/language",
        "/account/profile-type-updated",
        "/menu/$id",
        "/profile/$id",
        "/account/my-profile/edit",
        "/account/my-profile/view"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_withMenu": {
      "filePath": "_withMenu/route.tsx",
      "children": [
        "/_withMenu/account",
        "/_withMenu/earn",
        "/_withMenu/map",
        "/_withMenu/selections"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/tests": {
      "filePath": "tests.tsx"
    },
    "/tips/$placeId": {
      "filePath": "tips.$placeId/route.tsx",
      "children": [
        "/tips/$placeId/input",
        "/tips/$placeId/assets",
        "/tips/$placeId/error",
        "/tips/$placeId/info",
        "/tips/$placeId/profile",
        "/tips/$placeId/success",
        "/tips/$placeId/"
      ]
    },
    "/_withMenu/account": {
      "filePath": "_withMenu/account.tsx",
      "parent": "/_withMenu"
    },
    "/_withMenu/earn": {
      "filePath": "_withMenu/earn.tsx",
      "parent": "/_withMenu"
    },
    "/_withMenu/map": {
      "filePath": "_withMenu/map.tsx",
      "parent": "/_withMenu"
    },
    "/_withMenu/selections": {
      "filePath": "_withMenu/selections.tsx",
      "parent": "/_withMenu",
      "children": [
        "/_withMenu/selections/$id"
      ]
    },
    "/account/language": {
      "filePath": "account/language.tsx"
    },
    "/account/profile-type-updated": {
      "filePath": "account/profile-type-updated.tsx"
    },
    "/menu/$id": {
      "filePath": "menu.$id.tsx"
    },
    "/profile/$id": {
      "filePath": "profile.$id.tsx",
      "children": [
        "/profile/$id/fundraising"
      ]
    },
    "/tips/$placeId/input": {
      "filePath": "tips.$placeId/input/route.tsx",
      "parent": "/tips/$placeId",
      "children": [
        "/tips/$placeId/input/amount",
        "/tips/$placeId/input/confirm"
      ]
    },
    "/_withMenu/selections/$id": {
      "filePath": "_withMenu/selections.$id.tsx",
      "parent": "/_withMenu/selections"
    },
    "/account/my-profile/edit": {
      "filePath": "account/my-profile.edit.tsx"
    },
    "/account/my-profile/view": {
      "filePath": "account/my-profile.view.tsx"
    },
    "/profile/$id/fundraising": {
      "filePath": "profile.$id.fundraising.tsx",
      "parent": "/profile/$id"
    },
    "/tips/$placeId/assets": {
      "filePath": "tips.$placeId/assets.tsx",
      "parent": "/tips/$placeId"
    },
    "/tips/$placeId/error": {
      "filePath": "tips.$placeId/error.tsx",
      "parent": "/tips/$placeId"
    },
    "/tips/$placeId/info": {
      "filePath": "tips.$placeId/info.tsx",
      "parent": "/tips/$placeId"
    },
    "/tips/$placeId/profile": {
      "filePath": "tips.$placeId/profile.tsx",
      "parent": "/tips/$placeId"
    },
    "/tips/$placeId/success": {
      "filePath": "tips.$placeId/success.tsx",
      "parent": "/tips/$placeId"
    },
    "/tips/$placeId/": {
      "filePath": "tips.$placeId/index.tsx",
      "parent": "/tips/$placeId"
    },
    "/tips/$placeId/input/amount": {
      "filePath": "tips.$placeId/input/amount.tsx",
      "parent": "/tips/$placeId/input"
    },
    "/tips/$placeId/input/confirm": {
      "filePath": "tips.$placeId/input/confirm.tsx",
      "parent": "/tips/$placeId/input"
    }
  }
}
ROUTE_MANIFEST_END */
