/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as WithMenuRouteImport } from './routes/_withMenu/route'
import { Route as IndexImport } from './routes/index'
import { Route as WithMenuSelectionsImport } from './routes/_withMenu/selections'
import { Route as WithMenuMapImport } from './routes/_withMenu/map'
import { Route as WithMenuEarnImport } from './routes/_withMenu/earn'
import { Route as WithMenuAccountImport } from './routes/_withMenu/account'
import { Route as WithMenuSelectionsIdImport } from './routes/_withMenu/selections.$id'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const WithMenuRouteRoute = WithMenuRouteImport.update({
  id: '/_withMenu',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WithMenuSelectionsRoute = WithMenuSelectionsImport.update({
  id: '/selections',
  path: '/selections',
  getParentRoute: () => WithMenuRouteRoute,
} as any)

const WithMenuMapRoute = WithMenuMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => WithMenuRouteRoute,
} as any)

const WithMenuEarnRoute = WithMenuEarnImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => WithMenuRouteRoute,
} as any)

const WithMenuAccountRoute = WithMenuAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WithMenuRouteRoute,
} as any)

const WithMenuSelectionsIdRoute = WithMenuSelectionsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WithMenuSelectionsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_withMenu': {
      id: '/_withMenu'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithMenuRouteImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/_withMenu/account': {
      id: '/_withMenu/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof WithMenuAccountImport
      parentRoute: typeof WithMenuRouteImport
    }
    '/_withMenu/earn': {
      id: '/_withMenu/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof WithMenuEarnImport
      parentRoute: typeof WithMenuRouteImport
    }
    '/_withMenu/map': {
      id: '/_withMenu/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof WithMenuMapImport
      parentRoute: typeof WithMenuRouteImport
    }
    '/_withMenu/selections': {
      id: '/_withMenu/selections'
      path: '/selections'
      fullPath: '/selections'
      preLoaderRoute: typeof WithMenuSelectionsImport
      parentRoute: typeof WithMenuRouteImport
    }
    '/_withMenu/selections/$id': {
      id: '/_withMenu/selections/$id'
      path: '/$id'
      fullPath: '/selections/$id'
      preLoaderRoute: typeof WithMenuSelectionsIdImport
      parentRoute: typeof WithMenuSelectionsImport
    }
  }
}

// Create and export the route tree

interface WithMenuSelectionsRouteChildren {
  WithMenuSelectionsIdRoute: typeof WithMenuSelectionsIdRoute
}

const WithMenuSelectionsRouteChildren: WithMenuSelectionsRouteChildren = {
  WithMenuSelectionsIdRoute: WithMenuSelectionsIdRoute,
}

const WithMenuSelectionsRouteWithChildren =
  WithMenuSelectionsRoute._addFileChildren(WithMenuSelectionsRouteChildren)

interface WithMenuRouteRouteChildren {
  WithMenuAccountRoute: typeof WithMenuAccountRoute
  WithMenuEarnRoute: typeof WithMenuEarnRoute
  WithMenuMapRoute: typeof WithMenuMapRoute
  WithMenuSelectionsRoute: typeof WithMenuSelectionsRouteWithChildren
}

const WithMenuRouteRouteChildren: WithMenuRouteRouteChildren = {
  WithMenuAccountRoute: WithMenuAccountRoute,
  WithMenuEarnRoute: WithMenuEarnRoute,
  WithMenuMapRoute: WithMenuMapRoute,
  WithMenuSelectionsRoute: WithMenuSelectionsRouteWithChildren,
}

const WithMenuRouteRouteWithChildren = WithMenuRouteRoute._addFileChildren(
  WithMenuRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof WithMenuRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/account': typeof WithMenuAccountRoute
  '/earn': typeof WithMenuEarnRoute
  '/map': typeof WithMenuMapRoute
  '/selections': typeof WithMenuSelectionsRouteWithChildren
  '/selections/$id': typeof WithMenuSelectionsIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof WithMenuRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/account': typeof WithMenuAccountRoute
  '/earn': typeof WithMenuEarnRoute
  '/map': typeof WithMenuMapRoute
  '/selections': typeof WithMenuSelectionsRouteWithChildren
  '/selections/$id': typeof WithMenuSelectionsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_withMenu': typeof WithMenuRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_withMenu/account': typeof WithMenuAccountRoute
  '/_withMenu/earn': typeof WithMenuEarnRoute
  '/_withMenu/map': typeof WithMenuMapRoute
  '/_withMenu/selections': typeof WithMenuSelectionsRouteWithChildren
  '/_withMenu/selections/$id': typeof WithMenuSelectionsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/onboarding'
    | '/account'
    | '/earn'
    | '/map'
    | '/selections'
    | '/selections/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/onboarding'
    | '/account'
    | '/earn'
    | '/map'
    | '/selections'
    | '/selections/$id'
  id:
    | '__root__'
    | '/'
    | '/_withMenu'
    | '/onboarding'
    | '/_withMenu/account'
    | '/_withMenu/earn'
    | '/_withMenu/map'
    | '/_withMenu/selections'
    | '/_withMenu/selections/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithMenuRouteRoute: typeof WithMenuRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithMenuRouteRoute: WithMenuRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_withMenu",
        "/onboarding"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_withMenu": {
      "filePath": "_withMenu/route.tsx",
      "children": [
        "/_withMenu/account",
        "/_withMenu/earn",
        "/_withMenu/map",
        "/_withMenu/selections"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/_withMenu/account": {
      "filePath": "_withMenu/account.tsx",
      "parent": "/_withMenu"
    },
    "/_withMenu/earn": {
      "filePath": "_withMenu/earn.tsx",
      "parent": "/_withMenu"
    },
    "/_withMenu/map": {
      "filePath": "_withMenu/map.tsx",
      "parent": "/_withMenu"
    },
    "/_withMenu/selections": {
      "filePath": "_withMenu/selections.tsx",
      "parent": "/_withMenu",
      "children": [
        "/_withMenu/selections/$id"
      ]
    },
    "/_withMenu/selections/$id": {
      "filePath": "_withMenu/selections.$id.tsx",
      "parent": "/_withMenu/selections"
    }
  }
}
ROUTE_MANIFEST_END */
