export const mapAssets = {
  bar: "/parity/map/bar.svg",
  catBakery: "/parity/selections/cat-bakery.svg",
  catCoffee: "/parity/selections/cat-coffee.svg",
  categoryFilterCancel: "/parity/map/category-filter-cancel.svg",
  catSeafood: "/parity/selections/cat-seafood.svg",
  catVeg: "/parity/selections/cat-veg.svg",
  coffee: "/parity/map/coffee.svg",
  drawerHandleExpanded: "/parity/map/drawer-handle-expanded.svg",
  drawerHandleLow: "/parity/map/drawer-handle-low.svg",
  fastFood: "/parity/map/fast-food.svg",
  filterChevron: "/parity/map/filter-chevron.svg",
  fish: "/parity/map/fish.svg",
  locate: "/parity/map/locate.svg",
  mapBackground: "/parity/map/map-background.png",
  navAccount: "/parity/map/nav-account.svg",
  navAccountActive: "/parity/map/nav-account-active.svg",
  navBonuses: "/parity/map/nav-bonuses.svg",
  navBonusesActive: "/parity/map/nav-bonuses-active.svg",
  navMap: "/parity/map/nav-map.svg",
  navMapActive: "/parity/map/nav-map-active.svg",
  navWall: "/parity/map/nav-wall.svg",
  navWallActive: "/parity/map/nav-wall-active.svg",
  noodle: "/parity/map/noodle.svg",
  pin: "/parity/selections/pin.svg",
  pinGradient: "/parity/map/pin-gradient.svg",
  pizza: "/parity/map/pizza.svg",
  salad: "/parity/map/salad.svg",
  seafood: "/parity/map/seafood.svg",
  search: "/parity/qr/search.svg",
  searchClear: "/parity/map/search-clear.svg",
  zoomIn: "/parity/map/zoom-in.svg",
  zoomOut: "/parity/map/zoom-out.svg",
} as const

export const MAP_CATEGORY_TONES = {
  bakery: "bg-[#dab072]",
  coffee: "bg-[#0a78ff]",
  fish: "bg-[#2f619d]",
  seafood: "bg-[#e5454b]",
  veg: "bg-[#69c700]",
} as const
