// This file is generated by icon spritesheet generator

export const iconNames = [
	"MenuBoard",
	"Vector",
	"User Circle Outline",
	"Shape",
	"Globe Europe Africa Fill",
	"Frame 1580",
	"CoinsFill",
] as const

export type IconName = (typeof iconNames)[number]
