// This file is generated by icon spritesheet generator

export const iconNames = [
  "MenuBoard",
  "Check",
  "Vector",
  "User Circle Outline",
  "Shape",
  "Group 3",
  "Globe Europe Africa Fill",
  "Frame 951",
  "Frame 951 (1)",
  "Frame 948",
  "Frame 1580",
  "CoinsFill",
  "ChevronRight",
  "Arrowz",
] as const

export type IconName = (typeof iconNames)[number]
