// This file is generated by icon spritesheet generator

export const iconNames = [
  "MenuBoard",
  "Vector",
  "User Circle Outline",
  "Shape",
  "Group 3",
  "Globe Europe Africa Fill",
  "Frame 1580",
  "CoinsFill",
  "ChevronRight",
] as const

export type IconName = (typeof iconNames)[number]
